# Generated by Django 5.1.4 on 2024-12-09 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên dự án')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('status', models.CharField(choices=[('open', 'Mở'), ('closed', 'Đóng')], default='open', max_length=50, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên nhiệm vụ')),
                ('description', models.TextField(verbose_name='Mô tả nhiệm vụ')),
                ('status', models.CharField(choices=[('not started', 'Chưa bắt đầu'), ('in progress', 'Đang làm'), ('completed', 'Hoàn thành')], default='not started', max_length=50, verbose_name='Trạng thái')),
                ('due_date', models.DateTimeField(verbose_name='Ngày hết hạn')),
                ('assigned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người được phân công')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project', verbose_name='Dự án')),
            ],
        ),
    ]
